name: "coverage"

on: pull_request

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        run: yarn install
      - uses: artiomtr/jest-coverage-report-action@v2.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          threshold: 95
          test-script: "yarn test:coverage"
